# Command-line tools and runtimes
brew "git"
brew "tree"
brew "mysql"
brew "htop"
brew "wget"
brew "tmux"
brew "vim"
brew "node"
# PDF utilities (pdftotext, pdfimages) used by AI PDF reading workflows
brew "poppler"

# Desktop applications
cask "google-chrome"
cask "visual-studio-code"
cask "obsidian"
cask "raycast"
cask "cyberduck"
cask "iina"
cask "rstudio"
cask "google-drive"
cask "microsoft-office"
cask "figma"
cask "tempbox"
cask "linearmouse"
cask "zoom"
cask "slack"
cask "discord"
cask "chatgpt"
cask "claude"
cask "meetingbar"
cask "mactex-no-gui"
cask "notion"
cask "hiddenbar"
cask "tailscale"

# Terminal coding agents
cask "codex"
cask "claude-code"
